[variables]
NIXPACKS_NODE_VERSION = "26.5.0"
PORT = "3004"

[phases.setup]
nixPkgs = ["nodejs_26"]

[build]
cacheDirectories = [".next/cache", "node_modules/.cache"]

[start]
cmd = "next start -p 3004"
